# Generated by Django 4.0.6 on 2022-08-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='verify_code',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
    ]
